
(()=>{'use strict';
const D=window.LUMI_DATA||{categories:[],words:[],lessons:[]},LEG=window.LUMI_EXTRA||{},M=window.LUMI_MEGA||{dialogues:[],stories:[]};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').trim();
const KEY='lumi-v23-state';let S={view:'learn',xp:0,gems:100,streak:0,unlocked:1,completed:[],srs:{},mistakes:[]};try{Object.assign(S,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{};
let run=null,media=null,chunks=[],audioUrl=null;const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
function header(){top.innerHTML=`<div class="brand"><div class="mascot">🐱</div><div><h1>Lumi</h1><small>Rumänisch Schritt für Schritt</small></div></div><div class="stats"><span class="pill">🔥 ${S.streak}</span><span class="pill">💎 ${S.gems}</span><span class="pill">⭐ ${S.xp}</span></div>`}
function nav(){const items=[['learn','🏠','Lernen'],['practice','🧠','Üben'],['words','📚','Wörter'],['talk','💬','Sprechen'],['progress','📈','Fortschritt']];navEl.innerHTML=items.map(x=>`<button data-a="view" data-v="${x[0]}" class="${S.view===x[0]?'active':''}">${x[1]}<br>${x[2]}</button>`).join('')}
const top=document.getElementById('top'),main=$('#main'),navEl=$('#nav');
function render(){header();nav();({learn:learn,practice:practice,words:words,talk:talk,progress:progress}[S.view]||learn)()}
function learn(){let h=`<section class="hero"><div class="mascot">🐱</div><div><h2>Dein Lernpfad</h2><p>5.400 Wörter · 469 Lektionen · A1 bis C2</p></div></section><div class="grid"><button class="card" data-a="module" data-m="dialogues">💬 <b>1.000 Dialogsituationen</b><small>Alltag, Arbeit, Reise, Beziehung und mehr</small></button><button class="card" data-a="module" data-m="stories">📖 <b>300 Geschichten</b><small>Vom kurzen A1-Text bis C1</small></button><button class="card" data-a="module" data-m="grammar">🧩 <b>Grammatik</b><small>Präsens, Vergangenheit, Zukunft und mehr</small></button><button class="card" data-a="module" data-m="review">🎯 <b>Fällige Wiederholungen</b><small>${dueWords().length} Wörter sind heute fällig</small></button></div>`;
for(const c of D.categories){const ls=D.lessons.filter(l=>l.section===c.id);if(!ls.length)continue;h+=`<section class="section"><h2>${c.icon} ${esc(c.title)} <small>${esc(c.level)}</small></h2><p>${esc(c.description)}</p>${ls.slice(0,20).map(l=>{const i=l.index||0,locked=i>=S.unlocked;return `<button class="lesson ${locked?'locked':''}" data-a="lesson" data-i="${i}" ${locked?'disabled':''}><span><b>${esc(l.title)}</b><small>${esc(l.subtitle||'Wörter, Sätze, Hören und Sprechen')}</small></span><span>${S.completed.includes(i)?'✅':locked?'🔒':'▶️'}</span></button>`}).join('')}</section>`}main.innerHTML=h}
function practice(){main.innerHTML=`<section class="panel"><h2>Intelligent üben</h2><p>Fällige und unsichere Wörter kommen häufiger zurück.</p><div class="grid"><button class="card" data-a="start" data-mode="due">⏰ Fällige Wörter<small>${dueWords().length} heute</small></button><button class="card" data-a="start" data-mode="mistakes">🎯 Fehlertraining<small>${S.mistakes.length} gespeichert</small></button><button class="card" data-a="start" data-mode="random">⚡ Schnelltraining<small>12 gemischte Aufgaben</small></button></div></section>`}
function words(){main.innerHTML=`<section class="panel"><h2>Wörterbuch · ${D.words.length}</h2><input class="search" id="q" placeholder="Rumänisch oder Deutsch"><div id="wl"></div></section>`;drawWords('')}
function drawWords(q){q=norm(q);const ws=D.words.filter(w=>!q||norm(w.ro).includes(q)||norm(w.de).includes(q)).slice(0,120);$('#wl').innerHTML=ws.map(w=>`<div class="wordRow"><b>${esc(w.ro)}</b><span>${esc(w.de)}</span><button data-a="speak" data-t="${esc(w.ro)}">🔊</button></div>`).join('')}
function talk(){main.innerHTML=`<section class="panel"><h2>Gesprächstrainer</h2><p>Wähle eine Rolle. Der Offline-Modus arbeitet mit echten Dialogpfaden. Für freie KI-Gespräche kann später ein sicherer Backend-Endpunkt verbunden werden.</p><div class="grid">${['Restaurant','Arzt','Hotel','Dating','Arbeit','Telefon','Behörde','Reise'].map(x=>`<button class="card" data-a="role" data-role="${x}">💬 ${x}<small>Rollenspiel starten</small></button>`).join('')}</div></section>`}
function progress(){const known=Object.values(S.srs).filter(x=>x.box>=4).length;main.innerHTML=`<section class="panel"><h2>Fortschritt</h2><p>Abgeschlossene Lektionen: <b>${S.completed.length}</b></p><p>Sichere Wörter: <b>${known}</b></p><p>Fällige Wiederholungen: <b>${dueWords().length}</b></p><p>XP: <b>${S.xp}</b></p><button class="btn secondary" data-a="reset">Fortschritt zurücksetzen</button></section>`}
function module(m){if(m==='dialogues')return listDialogues();if(m==='stories')return listStories();if(m==='grammar')return grammar();if(m==='review')return start('due')}
function back(){return `<button class="btn secondary" data-a="view" data-v="learn">← Zurück</button>`}
function listDialogues(){main.innerHTML=`${back()}<section class="panel"><h2>1.000 Alltagssituationen</h2><div class="tabs">${['A1','A2','B1','B2','C1'].map(x=>`<button data-a="filterD" data-l="${x}">${x}</button>`).join('')}</div><div id="dl"></div></section>`;drawDialogues('A1')}
function drawDialogues(l){$('#dl').innerHTML=M.dialogues.filter(d=>d.level===l).slice(0,80).map(d=>`<button class="lesson" data-a="dialog" data-id="${d.id}"><span><b>${esc(d.title)}</b><small>${esc(d.scene)}</small></span><span>▶️</span></button>`).join('')}
function showDialog(id){const d=M.dialogues.find(x=>x.id===id);main.innerHTML=`${back()}<section class="panel"><h2>${esc(d.title)}</h2><p>${esc(d.scene)}</p>${d.turns.map(t=>`<div class="dialogTurn"><b>${t[0]}:</b> <button data-a="speak" data-t="${esc(t[1])}">🔊</button> ${esc(t[1])}<br><small>${esc(t[2])}</small></div>`).join('')}<button class="btn" data-a="roleStart" data-id="${id}">Rollenspiel starten</button></section>`}
function listStories(){main.innerHTML=`${back()}<section class="panel"><h2>300 Geschichten</h2><div class="tabs">${['A1','A2','B1','B2','C1'].map(x=>`<button data-a="filterS" data-l="${x}">${x}</button>`).join('')}</div><div id="sl"></div></section>`;drawStories('A1')}
function drawStories(l){$('#sl').innerHTML=M.stories.filter(s=>s.level===l).map(s=>`<button class="lesson" data-a="story" data-id="${s.id}"><span><b>${esc(s.title)}</b><small>${esc(s.seed)}</small></span><span>📖</span></button>`).join('')}
function showStory(id){const s=M.stories.find(x=>x.id===id);main.innerHTML=`${back()}<section class="panel"><h2>${esc(s.title)}</h2><button class="btn secondary" data-a="speak" data-t="${esc(s.ro)}">🔊 Text anhören</button><p class="storyText"><b>Rumänisch:</b><br>${esc(s.ro)}</p><details><summary>Deutsche Übersetzung</summary><p>${esc(s.de)}</p></details><h3>${esc(s.question)}</h3>${s.answers.map((a,i)=>`<button class="choice" data-a="storyAns" data-ok="${i===s.correct}">${esc(a)}</button>`).join('')}</section>`}
function grammar(){const gs=LEG.grammar||[];main.innerHTML=`${back()}<section class="panel"><h2>Grammatik vollständig erklärt</h2><p>Arbeite die Themen in Reihenfolge durch: Grundlagen → Präsens → Vergangenheit → Zukunft → komplexe Strukturen.</p>${gs.map((g,i)=>`<details ${i===0?'open':''}><summary><b>${esc(g.level)} · ${esc(g.title)}</b></summary><p>${esc(g.rule)}</p>${(g.forms||[]).map(x=>`<div class="dialogTurn"><b>${esc(x[0])}</b> ${esc(x[1])}</div>`).join('')}${(g.examples||[]).map(x=>`<div class="dialogTurn"><button data-a="speak" data-t="${esc(x[0])}">🔊</button> <b>${esc(x[0])}</b><br>${esc(x[1])}</div>`).join('')}</details>`).join('')}</section>`}
function dueWords(){const now=Date.now();return D.words.filter(w=>S.srs[w.id]&&S.srs[w.id].due<=now)}
function start(mode){let ws=mode==='due'?dueWords():mode==='mistakes'?D.words.filter(w=>S.mistakes.includes(w.id)):D.words.filter(w=>w.source==='curated');if(!ws.length)ws=D.words.filter(w=>w.source==='curated');run={items:shuffle(ws).slice(0,12).map((w,i)=>makeItem(w,i)),i:0,answered:false};exercise()}
function lesson(i){const l=D.lessons[i];const ws=l.wordIds.map(id=>D.words.find(w=>w.id===id)).filter(Boolean);run={lesson:i,items:ws.slice(0,12).map((w,n)=>makeItem(w,n)),i:0,answered:false};exercise()}
function makeItem(w,i){return {w,type:['meaning','sentence','listen','write','arrange','speak'][i%6]}}
function exercise(){const it=run.items[run.i],w=it.w,p=Math.round(run.i/run.items.length*100);top.innerHTML=`<div class="exerciseTop"><button class="x" data-a="close">×</button><div class="bar"><i style="width:${p}%"></i></div><b>${run.i+1}/${run.items.length}</b></div>`;navEl.innerHTML='';let h=`<div class="hero"><div class="mascot">🐱</div><div><b>${titleFor(it.type)}</b></div></div>`;
if(it.type==='meaning'){h+=`<h1 class="prompt">Was bedeutet das?</h1><div class="visual">${w.emoji||'📝'}</div><div class="target">${esc(w.ro)} <button data-a="speak" data-t="${esc(w.ro)}">🔊</button></div>${options(w,'de').map(x=>`<button class="choice" data-a="ans" data-v="${esc(x)}" data-ok="${norm(x)===norm(w.de)}">${esc(x)}</button>`).join('')}`}
if(it.type==='sentence'){h+=`<h1 class="prompt">Was bedeutet der Satz?</h1><div class="target">${esc(w.roEx)} <button data-a="speak" data-t="${esc(w.roEx)}">🔊</button></div>${options(w,'deEx').map(x=>`<button class="choice" data-a="ans" data-v="${esc(x)}" data-ok="${norm(x)===norm(w.deEx)}">${esc(x)}</button>`).join('')}`}
if(it.type==='listen'){h+=`<h1 class="prompt">Welchen Satz hörst du?</h1><button class="btn" data-a="speak" data-t="${esc(w.roEx)}">🔊 Anhören</button>${options(w,'deEx').map(x=>`<button class="choice" data-a="ans" data-v="${esc(x)}" data-ok="${norm(x)===norm(w.deEx)}">${esc(x)}</button>`).join('')}`}
if(it.type==='write'){h+=`<h1 class="prompt">Schreibe auf Rumänisch</h1><div class="target">${esc(w.de)}</div><div class="help"><button class="btn secondary" data-a="help" data-val="${esc(w.ro)}">💡 Rumänische Hilfe</button><div id="help" class="helpBox hidden"></div></div><input id="typed" class="search" placeholder="Rumänisch"><button class="btn" data-a="check" data-ok="${esc(w.ro)}">Prüfen</button>`}
if(it.type==='arrange'){const parts=w.roEx.replace(/[.!?]/g,'').split(/\s+/),mix=shuffle(parts.map((x,j)=>({x,id:j})));run.sel=[];run.parts=parts;h+=`<h1 class="prompt">Baue den Satz</h1><div class="target">${esc(w.deEx)}</div><button class="btn secondary" data-a="help" data-val="${esc(w.roEx)}">💡 Rumänische Hilfe</button><div id="help" class="helpBox hidden"></div><div id="target" class="chips"></div><div class="chips">${mix.map(x=>`<button class="chip" data-a="chip" data-id="${x.id}" data-word="${esc(x.x)}">${esc(x.x)}</button>`).join('')}</div><button class="btn" data-a="arrangeCheck" data-ok="${esc(parts.join(' '))}">Prüfen</button>`}
if(it.type==='speak'){h+=`<h1 class="prompt">Sprich den Satz nach</h1><div class="target">${esc(w.roEx)}</div><p><b>Deutsch:</b> ${esc(w.deEx)}</p><button class="btn secondary" data-a="speak" data-t="${esc(w.roEx)}">🔊 Vorhören</button><button class="btn" data-a="record">🎙️ Aufnahme starten</button><div id="recStatus"></div><audio id="audio" controls class="hidden"></audio>`}
main.innerHTML=h}
function titleFor(t){return ({meaning:'Wortbedeutung',sentence:'Satz verstehen',listen:'Hörverständnis',write:'Schreiben',arrange:'Satzbau',speak:'Aussprache'})[t]}
function options(w,f){const pool=D.words.filter(x=>x.cat===w.cat&&x.level===w.level&&x.id!==w.id).map(x=>x[f]).filter(Boolean);return shuffle([w[f],...shuffle([...new Set(pool)]).slice(0,3)])}
function grade(ok){const w=run.items[run.i].w;const old=S.srs[w.id]||{box:0};old.box=ok?Math.min(5,old.box+1):0;const days=[0,1,3,7,16,35][old.box];old.due=Date.now()+days*86400000;S.srs[w.id]=old;if(ok){S.xp+=10;S.mistakes=S.mistakes.filter(x=>x!==w.id)}else if(!S.mistakes.includes(w.id))S.mistakes.push(w.id);save()}
function feedback(ok){run.answered=true;grade(ok);const w=run.items[run.i].w;main.insertAdjacentHTML('beforeend',`<div class="feedback"><h2>${ok?'Richtig! Foarte bine!':'Noch nicht ganz.'}</h2><p><b>Rumänisch:</b> ${esc(w.roEx||w.ro)}</p><p><b>Deutsch:</b> ${esc(w.deEx||w.de)}</p><button class="btn" data-a="next">Weiter</button></div>`)}
function next(){if(run.i<run.items.length-1){run.i++;run.answered=false;exercise()}else{if(Number.isInteger(run.lesson)){if(!S.completed.includes(run.lesson))S.completed.push(run.lesson);S.unlocked=Math.max(S.unlocked,run.lesson+2);save()}S.view='learn';run=null;render()}}
function speak(t,slow=false){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='ro-RO';u.rate=slow?.72:.9;speechSynthesis.speak(u)}
async function record(){const b=document.querySelector('[data-a="record"]'),st=$('#recStatus'),a=$('#audio');if(media?.state==='recording'){media.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];media=new MediaRecorder(stream);media.ondataavailable=e=>e.data.size&&chunks.push(e.data);media.onstop=()=>{stream.getTracks().forEach(x=>x.stop());const blob=new Blob(chunks,{type:media.mimeType});if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=URL.createObjectURL(blob);a.src=audioUrl;a.classList.remove('hidden');st.innerHTML='<div class="feedback"><b>Aufnahme gespeichert.</b> Höre dich an und vergleiche Rhythmus und Aussprache.</div>';b.textContent='🎙️ Noch einmal aufnehmen';if(!run.answered)feedback(true)};media.start();b.textContent='⏹ Aufnahme beenden';st.textContent='Aufnahme läuft …'}catch(e){st.textContent='Mikrofon konnte nicht geöffnet werden.'}}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function role(role){const ds=M.dialogues.filter(d=>d.title.toLowerCase().includes(role.toLowerCase())).slice(0,1);if(ds.length)return showDialog(ds[0].id);main.innerHTML=`${back()}<section class="panel"><h2>${esc(role)}</h2><p>Für dieses Rollenspiel wird ein passender Dialogpfad verwendet.</p></section>`}
document.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a;if(a==='view'){S.view=b.dataset.v;save();render()}else if(a==='module')module(b.dataset.m);else if(a==='lesson')lesson(+b.dataset.i);else if(a==='start')start(b.dataset.mode);else if(a==='speak')speak(b.dataset.t,b.dataset.slow==='1');else if(a==='filterD')drawDialogues(b.dataset.l);else if(a==='filterS')drawStories(b.dataset.l);else if(a==='dialog')showDialog(+b.dataset.id);else if(a==='story')showStory(+b.dataset.id);else if(a==='storyAns'){b.classList.add(b.dataset.ok==='true'?'correct':'wrong')}else if(a==='role')role(b.dataset.role);else if(a==='ans'&&!run.answered){b.classList.add(b.dataset.ok==='true'?'correct':'wrong');feedback(b.dataset.ok==='true')}else if(a==='help'){const h=$('#help');h.textContent='Rumänisch: '+b.dataset.val;h.classList.remove('hidden');speak(b.dataset.val,true)}else if(a==='check'&&!run.answered){feedback(norm($('#typed').value)===norm(b.dataset.ok))}else if(a==='chip'){if(b.classList.contains('used'))return;b.classList.add('used');run.sel.push(b.dataset.word);$('#target').textContent=run.sel.join(' ')}else if(a==='arrangeCheck'&&!run.answered){feedback(norm(run.sel.join(' '))===norm(b.dataset.ok))}else if(a==='record')record();else if(a==='next')next();else if(a==='close'){run=null;S.view='learn';render()}else if(a==='reset'){localStorage.removeItem(KEY);location.reload()}});
document.addEventListener('input',e=>{if(e.target.id==='q')drawWords(e.target.value)});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
})();
