const D=window.LUMI_DATA; const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DEFAULT={xp:0,gems:100,streak:0,lastDate:'',minutes:0,answers:0,correct:0,completed:{},wordStats:{}};
let S;try{S={...DEFAULT,...JSON.parse(localStorage.getItem('lumiFunctional')||'{}')}}catch{S={...DEFAULT}}
let run=null;
function save(){try{localStorage.setItem('lumiFunctional',JSON.stringify(S))}catch{}renderStats()}
function norm(t){return String(t||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[.,!?;:„”"']/g,'').trim()}
function renderStats(){$('#xp').textContent=S.xp;$('#gems').textContent=S.gems;$('#streak').textContent=S.streak;const p=Math.min(100,Math.round(S.minutes/15*100));$('#goalText').textContent=`${S.minutes} / 15 Minuten`;$('#goalBar').style.width=p+'%'}
function today(){return new Date().toISOString().slice(0,10)}function touchStreak(){const t=today();if(S.lastDate===t)return;const y=new Date(Date.now()-864e5).toISOString().slice(0,10);S.streak=S.lastDate===y?S.streak+1:1;S.lastDate=t}
function lessonUnlocked(i){return i===0||!!S.completed[D.lessons[i-1].id]}
function renderCourse(){const root=$('#course');root.innerHTML='';D.categories.forEach(cat=>{const sec=document.createElement('section');sec.className='section';sec.innerHTML=`<div class="sectionHead" style="background:${cat.color}"><div class="icon">${cat.icon}</div><div><h2>${cat.title}</h2><p>${cat.description}</p></div></div><div class="path"></div>`;const path=sec.querySelector('.path');D.lessons.filter(l=>l.section===cat.id).forEach(l=>{const unlocked=lessonUnlocked(l.index),done=S.completed[l.id];const row=document.createElement('div');row.className='nodeWrap';row.innerHTML=`<button class="node ${done?'done':unlocked?'unlocked':''} ${unlocked&&!done&&D.lessons.findIndex(x=>!S.completed[x.id])===l.index?'current':''}" data-id="${l.id}" aria-label="${l.title}">${done?'★':unlocked?l.icon:'🔒'}${done?'<span class="check">✓</span>':''}</button><div class="nodeLabel ${unlocked?'':'lockedLabel'}"><b>${l.title}</b><span>${unlocked?l.subtitle:'Vorherige Lektion abschließen'}</span></div>`;path.append(row)});root.append(sec)});$$('.node').forEach(b=>b.onclick=()=>{const l=D.lessons.find(x=>x.id===b.dataset.id);if(!lessonUnlocked(l.index))return toast('Diese Lektion ist noch gesperrt.');startLesson(l)})}
function show(id){$$('.screen').forEach(s=>s.classList.add('hidden'));$(id).classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function wordsFor(l){return l.wordIds.map(id=>D.words.find(w=>w.id===id)).filter(Boolean)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function makeExercises(l){const ws=wordsFor(l),ex=[];ws.forEach((w,i)=>{ex.push({type:'choice',w});ex.push({type:'listen',w});ex.push({type:'type',w});ex.push({type:'arrange',w})});return shuffle(ex).slice(0,10)}
function startLesson(l){run={lesson:l,items:makeExercises(l),i:0,score:0,hearts:5,start:Date.now(),answered:false};show('#screenLesson');renderExercise()}
function distract(w,field){return shuffle(D.words.filter(x=>x.id!==w.id&&x.cat===w.cat).map(x=>x[field])).slice(0,3)}
function speak(t){if(!('speechSynthesis'in window))return toast('Sprachausgabe nicht verfügbar.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='ro-RO';u.rate=.82;speechSynthesis.speak(u)}
function renderExercise(){if(run.i>=run.items.length||run.hearts<=0)return finishLesson();const e=run.items[run.i],w=e.w,p=Math.round(run.i/run.items.length*100);$('#lessonProgress').style.width=p+'%';$('#hearts').textContent='❤ '+run.hearts;run.answered=false;let h=`<div class="question"><div class="questionMascot"><img src="assets/lumi.svg"><div class="bubble">${promptFor(e.type)}</div></div>`;
if(e.type==='choice'){const opts=shuffle([w.de,...distract(w,'de')]);h+=`<h1>Was bedeutet „${w.ro}“?</h1><p class="hint">Wähle die richtige Übersetzung.</p><div class="answers">${opts.map(o=>`<button class="answer" data-value="${esc(o)}">${o}</button>`).join('')}</div>`}
if(e.type==='listen'){const opts=shuffle([w.ro,...distract(w,'ro')]);h+=`<h1>Was hörst du?</h1><button class="audioBtn" id="play">🔊</button><div class="answers" style="margin-top:22px">${opts.map(o=>`<button class="answer" data-value="${esc(o)}">${o}</button>`).join('')}</div>`}
if(e.type==='type'){h+=`<h1>Übersetze ins Rumänische</h1><p class="hint">${w.de}</p><input class="typed" id="typed" autocomplete="off" placeholder="Auf Rumänisch schreiben …"><button class="primary wide" id="check">Prüfen</button>`}
if(e.type==='arrange'){const pieces=shuffle(w.roEx.replace(/[.!?]/g,'').split(' '));h+=`<h1>Bilde den Satz</h1><p class="hint">${w.deEx}</p><div class="arrangeTarget" id="target"></div><div class="chips">${pieces.map((x,i)=>`<button class="wordChip" data-word="${esc(x)}" data-n="${i}">${x}</button>`).join('')}</div><button class="primary wide" id="checkArrange">Prüfen</button>`}h+='</div>';$('#exercise').innerHTML=h;
if($('#play')){$('#play').onclick=()=>speak(w.ro);setTimeout(()=>speak(w.ro),250)}
$$('.answer').forEach(b=>b.onclick=()=>checkAnswer(b,b.dataset.value,e.type==='choice'?w.de:w.ro,w));if($('#check')){$('#check').onclick=()=>checkAnswer($('#typed'),$('#typed').value,w.ro,w);$('#typed').onkeydown=x=>{if(x.key==='Enter')$('#check').click()}}
$$('.wordChip').forEach(b=>b.onclick=()=>{if(b.classList.contains('used'))return;b.classList.add('used');const c=document.createElement('button');c.className='wordChip';c.textContent=b.dataset.word;c.onclick=()=>{b.classList.remove('used');c.remove()};$('#target').append(c)});if($('#checkArrange'))$('#checkArrange').onclick=()=>checkAnswer($('#target'),[...$('#target').children].map(x=>x.textContent).join(' '),w.roEx.replace(/[.!?]/g,''),w)}
function promptFor(t){return {choice:'Ordne die Bedeutung zu.',listen:'Hör genau hin.',type:'Schreib die Übersetzung.',arrange:'Setze den Satz zusammen.'}[t]}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function checkAnswer(el,given,correct,w){if(run.answered)return;run.answered=true;const ok=norm(given)===norm(correct);S.answers++;if(ok){S.correct++;S.xp+=10;run.score++;S.wordStats[w.id]=(S.wordStats[w.id]||0)+1}else{run.hearts--;S.wordStats[w.id]=Math.max(0,(S.wordStats[w.id]||0)-1)}save();if(el.classList)el.classList.add(ok?'correct':'wrong');const box=document.createElement('div');box.className='feedback '+(ok?'':'wrong');box.innerHTML=`<div class="feedbackRow"><div><b>${ok?'Richtig! Foarte bine!':'Noch nicht ganz.'}</b><small>${ok?w.roEx:`Richtig: ${correct}`}</small></div><button class="primary" id="next">Weiter</button></div>`;document.body.append(box);$('#next').onclick=()=>{box.remove();run.i++;renderExercise()}}
function finishLesson(){const pct=Math.round(run.score/run.items.length*100),passed=pct>=60;touchStreak();S.minutes+=Math.max(1,Math.round((Date.now()-run.start)/60000));if(passed){S.completed[run.lesson.id]={score:pct,date:today()};S.gems+=10}else S.gems+=2;save();$('#doneTitle').textContent=passed?'Lektionenpunkt freigeschaltet!':'Fast geschafft';$('#doneText').textContent=passed?'Die nächste Lektion ist jetzt verfügbar.': 'Du brauchst mindestens 60 %. Starte die Lektion einfach erneut.';$('#doneScore').textContent=pct+'%';$('#doneXp').textContent='+'+(run.score*10)+' XP';show('#screenDone')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
$('#quitLesson').onclick=()=>{document.querySelector('.feedback')?.remove();show('#screenPath')};$('#doneContinue').onclick=()=>{renderCourse();show('#screenPath')};$('#homeLogo').onclick=()=>{renderCourse();show('#screenPath')};
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};
$('#practiceBtn').onclick=()=>{const weak=Object.entries(S.wordStats).sort((a,b)=>a[1]-b[1]).slice(0,4).map(([id])=>+id);const ids=weak.length>=4?weak:D.lessons.find(l=>!S.completed[l.id])?.wordIds||D.lessons[0].wordIds;startLesson({...D.lessons[0],id:'practice',title:'Persönliches Training',wordIds:ids})};
$('#wordsBtn').onclick=()=>{openModal(`<h1>Wörterbuch</h1><p>240 wichtige Alltagswörter aus deinem Lernpfad.</p><input class="search" id="search" placeholder="Deutsch oder Rumänisch suchen"><div class="dictionary" id="dict"></div>`);const render=()=>{const q=norm($('#search').value);$('#dict').innerHTML=D.words.filter(w=>!q||norm(w.ro).includes(q)||norm(w.de).includes(q)).map(w=>`<div class="wordCard"><span>${w.emoji}</span> <b>${w.ro}</b><p>${w.de}</p><button class="wordChip" data-say="${esc(w.ro)}">🔊 Anhören</button></div>`).join('');$$('[data-say]').forEach(b=>b.onclick=()=>speak(b.dataset.say))};$('#search').oninput=render;render()};
$('#profileBtn').onclick=()=>{const acc=S.answers?Math.round(S.correct/S.answers*100):0;openModal(`<h1>Dein Fortschritt</h1><div class="profileGrid"><div><b>${Object.keys(S.completed).length}/60</b><span>Lektionen</span></div><div><b>${S.xp}</b><span>XP</span></div><div><b>${acc}%</b><span>Trefferquote</span></div></div><h2 style="margin-top:24px">Lernstand</h2><p>${Object.keys(S.completed).length<10?'Du baust gerade deine Grundlagen auf.':Object.keys(S.completed).length<30?'Du kannst schon viele Alltagssituationen bewältigen.':'Du hast einen starken Lernfortschritt erreicht.'}</p><button class="primary" id="reset" style="background:#d75361;box-shadow:0 5px 0 #a62f3a">Fortschritt zurücksetzen</button>`);$('#reset').onclick=()=>{if(confirm('Wirklich alles zurücksetzen?')){try{localStorage.removeItem('lumiFunctional')}catch{}location.reload()}}};
renderStats();renderCourse();show('#screenPath');if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});