'use strict';
const D=window.LUMI_DATA; const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DEFAULT={xp:0,gems:100,streak:0,lastDate:'',minutes:0,answers:0,correct:0,completed:{},wordStats:{},voiceName:'',dark:false};
let S;try{S={...DEFAULT,...JSON.parse(localStorage.getItem('lumiV7')||localStorage.getItem('lumiV3')||'{}')}}catch{S={...DEFAULT}}
let run=null, voices=[],roVoice=null, recognition=null;
const X=window.LUMI_EXTRA||{grammar:[],dialogues:[],stories:[]};
const G=window.LUMI_GLOSSARY||[];
const GLOSSARY_MAP=new Map(G.map(([ro,de])=>[norm(ro),de]));
const COURSE_SECTIONS=D.categories.map((c,idx)=>({
  ...c, from:idx*15+1, to:idx*15+15,
  code: idx<2?'A1.1':idx<4?'A1.2':idx<7?'A2':idx<10?'B1':idx===10?'B2':'B2+',
  color:['#31b875','#ed9b3a','#e76f51','#5b8def','#4776c9','#7161c5','#9761c7','#dd6375','#dc7b45','#3da9a0','#6c8d36','#b88722'][idx%12]
}));
function makeLessons(){return COURSE_SECTIONS.flatMap((cat,ci)=>Array.from({length:15},(_,j)=>{
  const n=ci*15+j+1;
  const base=D.words.filter(w=>w.cat===cat.id);
  const count=n<=30?4:n<=90?5:6;
  const start=(j*3)%Math.max(1,base.length);
  const wordIds=Array.from({length:count},(_,k)=>(base[(start+k)%base.length]||D.words[(n+k)%D.words.length]).id);
  const phase=j===14?'Kapiteltest':j%5===0?'Neue Wörter':j%5===1?'Hören & verstehen':j%5===2?'Sätze bilden':j%5===3?'Sprechen': 'Alltag anwenden';
  return {id:`L${String(n).padStart(3,'0')}`,index:n-1,number:n,level:cat.code,section:cat.id,title:`${cat.title} ${j+1}`,subtitle:`${phase} · ${cat.code}`,icon:j===14?'🏆':cat.icon,wordIds,checkpoint:j===14};
}))}
const LESSONS=makeLessons();
function save(){try{localStorage.setItem('lumiV7',JSON.stringify(S))}catch{}renderStats()}
function norm(t){return String(t||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9ăâîșşțţ\s]/gi,' ').replace(/\s+/g,' ').trim()}
function similarity(a,b){a=norm(a);b=norm(b);if(a===b)return 1;const aw=a.split(' '),bw=b.split(' ');const hit=aw.filter(x=>bw.includes(x)).length;return hit/Math.max(aw.length,bw.length,1)}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function today(){return new Date().toISOString().slice(0,10)}
function touchStreak(){const t=today();if(S.lastDate===t)return;const y=new Date(Date.now()-864e5).toISOString().slice(0,10);S.streak=S.lastDate===y?S.streak+1:1;S.lastDate=t}
function renderStats(){$('#xp').textContent=S.xp;$('#gems').textContent=S.gems;$('#streak').textContent=S.streak;const p=Math.min(100,Math.round(S.minutes/15*100));$('#goalText').textContent=`${S.minutes} / 15 Minuten`;$('#goalBar').style.width=p+'%';$('#courseProgress').textContent=`${Object.keys(S.completed).filter(k=>k.startsWith('L')).length} von ${LESSONS.length}`; const next=LESSONS.find(l=>!S.completed[l.id])||LESSONS.at(-1); if($('#continueText'))$('#continueText').textContent=`${next.level} · ${next.title}`}
function lessonUnlocked(i){return i===0||!!S.completed[LESSONS[i-1].id]}
function show(id){$$('.screen').forEach(s=>s.classList.add('hidden'));$(id).classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function renderCourse(){const root=$('#course');root.innerHTML='';COURSE_SECTIONS.forEach(level=>{const sec=document.createElement('section');sec.className='section';const doneCount=LESSONS.filter(l=>l.section===level.id&&S.completed[l.id]).length;sec.innerHTML=`<div class="sectionHead" style="background:${level.color}"><div class="icon">${level.icon}</div><div><span class="levelPill">${level.code} · ${doneCount}/15</span><h2>${esc(level.title)}</h2><p>${esc(level.desc||'Wortschatz, Hören, Sprechen und Alltag')}</p></div></div><div class="path"></div>`;const path=sec.querySelector('.path');LESSONS.filter(l=>l.section===level.id).forEach(l=>{const unlocked=lessonUnlocked(l.index),done=S.completed[l.id],current=unlocked&&!done&&LESSONS.findIndex(x=>!S.completed[x.id])===l.index;const row=document.createElement('div');row.className='nodeWrap';row.innerHTML=`<button class="node ${done?'done':unlocked?'unlocked':''} ${current?'current':''} ${l.checkpoint?'checkpoint':''}" data-id="${l.id}" aria-label="${esc(l.title)}">${done?'★':unlocked?l.icon:'🔒'}${done?'<span class="check">✓</span>':''}</button><div class="nodeLabel ${unlocked?'':'lockedLabel'}"><b><span class="lessonNo">${l.number}</span> ${esc(l.title)}</b><span>${unlocked?esc(l.subtitle):'Vorherigen Lernpunkt abschließen'}</span></div>`;path.append(row)});root.append(sec)});$$('.node').forEach(b=>b.onclick=()=>{const l=LESSONS.find(x=>x.id===b.dataset.id);if(!lessonUnlocked(l.index))return toast('Dieser Lernpunkt ist noch gesperrt.');startLesson(l)})}
function loadVoices(){voices=speechSynthesis?.getVoices?.()||[];roVoice=voices.find(v=>v.name===S.voiceName&&/^ro/i.test(v.lang))||voices.find(v=>/^ro[-_]/i.test(v.lang))||voices.find(v=>/^ro$/i.test(v.lang))||null;renderVoiceBanner()}
function renderVoiceBanner(){const el=$('#voiceBanner');if(!('speechSynthesis'in window)){el.className='voiceBanner bad';el.innerHTML='<b>🔇 Keine Sprachausgabe verfügbar</b><span>Dieser Browser unterstützt die Sprachfunktion nicht.</span>';return}if(roVoice){el.className='voiceBanner good';el.innerHTML=`<b>🔊 Rumänische Stimme aktiv</b><span>${esc(roVoice.name)} · ${esc(roVoice.lang)}</span>`}else{el.className='voiceBanner warn';el.innerHTML='<b>⚠️ Keine rumänische Stimme gefunden</b><span>Die App verwendet absichtlich keine deutsche Ersatzstimme. Installiere eine rumänische Systemstimme oder teste einen anderen Browser.</span>'}}
function speak(text,slow=false){if(!('speechSynthesis'in window))return toast('Sprachausgabe ist auf diesem Gerät nicht verfügbar.');if(!roVoice){renderVoiceBanner();return toast('Keine rumänische Stimme installiert.')}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ro-RO';u.voice=roVoice;u.rate=slow?.62:.82;u.pitch=1;u.volume=1;speechSynthesis.speak(u)}
function voiceSettings(){const options=voices.filter(v=>/^ro/i.test(v.lang)).map(v=>`<option value="${esc(v.name)}" ${v.name===roVoice?.name?'selected':''}>${esc(v.name)} (${esc(v.lang)})</option>`).join('');openModal(`<h1>Rumänische Aussprache</h1><p>Die App nutzt die rumänische Stimme deines Geräts. Eine echte Muttersprachler-Aufnahme ist dadurch nicht garantiert, aber eine falsche deutsche Stimme wird nicht verwendet.</p>${options?`<label class="fieldLabel">Rumänische Stimme<select id="voiceSelect">${options}</select></label><div class="voiceTest"><button class="primary" id="testVoice">▶ Beispielsatz anhören</button><button class="secondary" id="slowVoice">🐢 Langsam anhören</button></div>`:'<div class="notice bad"><b>Keine rumänische Stimme vorhanden.</b><p>Auf iPhone: Einstellungen → Bedienungshilfen → Gesprochene Inhalte → Stimmen → Rumänisch. Danach die App vollständig schließen und neu öffnen.</p></div>'}<hr><h2>Mikrofonprüfung</h2><p>Die Browser-Spracherkennung prüft, ob dein Satz als richtiges Rumänisch erkannt wird. Sie ersetzt keine exakte phonetische Bewertung durch einen Sprachlehrer.</p>`);if($('#voiceSelect'))$('#voiceSelect').onchange=e=>{S.voiceName=e.target.value;save();loadVoices()};if($('#testVoice'))$('#testVoice').onclick=()=>speak('Bună seara! Mă bucur să te cunosc.');if($('#slowVoice'))$('#slowVoice').onclick=()=>speak('Bună seara! Mă bucur să te cunosc.',true)}
function wordsFor(l){return l.wordIds.map(id=>D.words.find(w=>w.id===id)).filter(Boolean)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function difficulty(l){return l.number<=30?1:l.number<=60?2:l.number<=90?3:l.number<=120?4:l.number<=140?5:6}
const SECTION_TEXTS={
 basics:{level:'A1',ro:'Bună! Eu sunt Ana. Locuiesc în România. Dimineața spun „bună dimineața”, iar seara spun „bună seara”. Când primesc ajutor, spun „mulțumesc”.',de:'Hallo! Ich bin Ana. Ich wohne in Rumänien. Morgens sage ich „Guten Morgen“, abends sage ich „Guten Abend“. Wenn ich Hilfe bekomme, sage ich „Danke“.',q:'Was sagt Ana, wenn sie Hilfe bekommt?',answers:['mulțumesc','la revedere','nu'],correct:0},
 family:{level:'A1',ro:'Familia mea este mică. Am o mamă, un tată și o soră. Sora mea se numește Elena. Duminică mâncăm împreună.',de:'Meine Familie ist klein. Ich habe eine Mutter, einen Vater und eine Schwester. Meine Schwester heißt Elena. Am Sonntag essen wir zusammen.',q:'Wie heißt die Schwester?',answers:['Elena','Maria','Ana'],correct:0},
 food:{level:'A1',ro:'Dimineața beau cafea și mănânc pâine. La prânz comand o supă. Seara gătesc paste cu legume.',de:'Morgens trinke ich Kaffee und esse Brot. Mittags bestelle ich eine Suppe. Abends koche ich Nudeln mit Gemüse.',q:'Was bestellt die Person mittags?',answers:['o supă','o cafea','un bilet'],correct:0},
 home:{level:'A1',ro:'Locuiesc într-un apartament mic. Bucătăria este lângă sufragerie. În dormitor am un pat și un dulap.',de:'Ich wohne in einer kleinen Wohnung. Die Küche ist neben dem Wohnzimmer. Im Schlafzimmer habe ich ein Bett und einen Schrank.',q:'Was steht im Schlafzimmer?',answers:['un pat','un autobuz','o masă la restaurant'],correct:0},
 transport:{level:'A2',ro:'Merg la gară cu autobuzul. Cumpăr un bilet și întreb de la ce peron pleacă trenul. Trenul are zece minute întârziere.',de:'Ich fahre mit dem Bus zum Bahnhof. Ich kaufe eine Fahrkarte und frage, von welchem Bahnsteig der Zug abfährt. Der Zug hat zehn Minuten Verspätung.',q:'Wie viel Verspätung hat der Zug?',answers:['zece minute','o oră','două zile'],correct:0},
 city:{level:'A2',ro:'În centru caut o farmacie și un bancomat. Întreb un trecător, iar el îmi arată drumul. Farmacia este vizavi de bancă.',de:'Im Zentrum suche ich eine Apotheke und einen Geldautomaten. Ich frage einen Passanten und er zeigt mir den Weg. Die Apotheke liegt gegenüber der Bank.',q:'Wo ist die Apotheke?',answers:['vizavi de bancă','lângă gară','în hotel'],correct:0},
 work:{level:'B1',ro:'Lucrez într-un birou și încep la ora opt. Dimineața răspund la e-mailuri, iar după-amiaza particip la o ședință. Uneori lucrez de acasă.',de:'Ich arbeite in einem Büro und beginne um acht Uhr. Morgens beantworte ich E-Mails, nachmittags nehme ich an einer Besprechung teil. Manchmal arbeite ich von zu Hause.',q:'Was macht die Person nachmittags?',answers:['participă la o ședință','merge la medic','cumpără un bilet'],correct:0},
 health:{level:'A2',ro:'Nu mă simt bine. Mă doare gâtul și am febră. Sun la medic și primesc o programare pentru după-amiază.',de:'Ich fühle mich nicht gut. Mein Hals tut weh und ich habe Fieber. Ich rufe beim Arzt an und bekomme einen Termin für den Nachmittag.',q:'Welche Beschwerden hat die Person?',answers:['durere în gât și febră','foame și sete','o întârziere'],correct:0},
 travel:{level:'A2',ro:'La hotel am o rezervare pentru două nopți. Camera este liniștită, dar prosopul lipsește. Sun la recepție și cer un prosop nou.',de:'Im Hotel habe ich eine Reservierung für zwei Nächte. Das Zimmer ist ruhig, aber das Handtuch fehlt. Ich rufe die Rezeption an und bitte um ein neues Handtuch.',q:'Was fehlt im Zimmer?',answers:['prosopul','patul','ușa'],correct:0},
 feelings:{level:'B1',ro:'Astăzi sunt fericit, pentru că mă întâlnesc cu prietena mea. Vorbim despre ziua noastră și facem planuri pentru weekend.',de:'Heute bin ich glücklich, weil ich meine Freundin treffe. Wir sprechen über unseren Tag und machen Pläne für das Wochenende.',q:'Warum ist die Person glücklich?',answers:['Se întâlnește cu prietena lui.','Trebuie să lucreze.','A pierdut trenul.'],correct:0},
 leisure:{level:'B1',ro:'Sâmbătă merg cu prietenii la un meci de fotbal. Echipa noastră câștigă cu doi la unu. După meci mâncăm împreună.',de:'Am Samstag gehe ich mit Freunden zu einem Fußballspiel. Unsere Mannschaft gewinnt zwei zu eins. Nach dem Spiel essen wir gemeinsam.',q:'Wie endet das Spiel?',answers:['doi la unu','zero la zero','trei la patru'],correct:0},
 conversation:{level:'B2',ro:'Într-o conversație nu înțeleg un cuvânt. Îl rog pe interlocutor să vorbească mai încet și să repete propoziția. Apoi pot continua discuția.',de:'In einem Gespräch verstehe ich ein Wort nicht. Ich bitte meinen Gesprächspartner, langsamer zu sprechen und den Satz zu wiederholen. Danach kann ich das Gespräch fortsetzen.',q:'Was bittet die Person den Gesprächspartner zu tun?',answers:['să vorbească mai încet și să repete','să plece imediat','să scrie un bilet'],correct:0}
};
function exerciseSolution(e,w){
  if(['arrange','speak','translateSentence','dictation','sentenceChoice','listenSentence'].includes(e.type)) return {ro:w.roEx.replace(/[.!?]+$/,''),de:w.deEx.replace(/[.!?]+$/,'')};
  if(e.type==='story') return {ro:e.story.answers[e.story.correct],de:e.story.answersDe?.[e.story.correct]||e.story.answers[e.story.correct]};
  return {ro:w.ro,de:w.de};
}
function makeExercises(l){
 const ws=wordsFor(l),d=difficulty(l),items=[];
 // Von Anfang an: Wort, Satz, Hören, Schreiben, Sprechen und Textverständnis.
 const a=ws[0],b=ws[1]||a,c=ws[2]||a,dw=ws[3]||a;
 items.push({type:'choice',w:a});
 items.push({type:'sentenceChoice',w:b});
 items.push({type:'listenSentence',w:c});
 items.push({type:'type',w:dw});
 items.push({type:'arrange',w:a});
 items.push({type:'speak',w:b});
 if(d>=2) items.push({type:'translateSentence',w:c});
 if(d>=3) items.push({type:'dictation',w:dw});
 if(l.number%3===0||l.checkpoint) items.push({type:'story',w:a,story:SECTION_TEXTS[l.section]});
 if(d>=4) items.push({type:'freeSpeak',w:a});
 return items.slice(0,l.checkpoint?10:8);
}
function startLesson(l){run={lesson:l,items:makeExercises(l),i:0,score:0,hearts:5,start:Date.now(),answered:false};show('#screenLesson');renderExercise()}
function distract(w,field){let pool=D.words.filter(x=>x.id!==w.id&&x.cat===w.cat).map(x=>x[field]);if(pool.length<3)pool=D.words.filter(x=>x.id!==w.id).map(x=>x[field]);return shuffle([...new Set(pool)]).slice(0,3)}
function clickableRomanian(text,translation){const tokens=String(text).split(/(\s+|[.,!?;:])/);return `<span class="clickSentence" data-sentence-de="${esc(translation)}">${tokens.map(tok=>{if(/^\s+$/.test(tok)||/^[.,!?;:]$/.test(tok))return tok;const clean=norm(tok);const found=D.words.find(w=>norm(w.ro)===clean);const de=found?.de||GLOSSARY_MAP.get(clean)||'Im Satz: '+translation;return `<button class="tapWord" data-ro="${esc(tok)}" data-de="${esc(de)}">${esc(tok)}</button>`}).join('')}</span>`}
function hintPairs(de,ro){
  const special={
    'guten abend':['bună','seara'], 'guten morgen':['bună','dimineața'],
    'auf wiedersehen':['la','revedere'], 'bis bald':['pe','curând'],
    'gern geschehen':['cu','plăcere'], 'entschuldigen sie':['scuzați-mă','scuzați-mă']
  };
  const deWords=String(de).trim().split(/\s+/), key=norm(de), roWords=special[key]||String(ro).trim().split(/\s+/);
  return deWords.map((word,i)=>({de:word,ro:roWords[i]||String(ro)}));
}
function germanHintPrompt(de,ro){return `<div class="germanHintPrompt">${hintPairs(de,ro).map((x,i)=>`<button class="germanHintWord" data-ro="${esc(x.ro)}" aria-expanded="false"><strong>${esc(x.de)}</strong><span class="hiddenHint">${esc(x.ro)}</span><small>Antippen für Hilfe</small></button>`).join('')}</div><p class="tapHelp">💡 Tippe nur dann auf ein deutsches Wort, wenn du Hilfe brauchst. Beim Antippen hörst du sofort die rumänische Lösung.</p>`}
function bindGermanHints(){ $$('.germanHintWord').forEach(b=>b.onclick=e=>{e.stopPropagation();const open=b.classList.toggle('revealed');b.setAttribute('aria-expanded',String(open));if(open)speak(b.dataset.ro)}); }
function bindWordTips(){ $$('.tapWord').forEach(b=>b.onclick=e=>{e.stopPropagation();speak(b.dataset.ro);const tip=$('#wordTip');tip.innerHTML=`<b>${esc(b.dataset.ro)}</b><span>${esc(b.dataset.de)}</span><button id="tipSpeak" aria-label="Noch einmal anhören">🔊</button>`;tip.classList.remove('hidden');const r=b.getBoundingClientRect();tip.style.left=Math.min(window.innerWidth-220,Math.max(8,r.left))+'px';tip.style.top=Math.max(8,r.bottom+8)+'px';$('#tipSpeak').onclick=()=>speak(b.dataset.ro)});}
document.addEventListener('click',e=>{if(!e.target.closest('.tapWord')&&!e.target.closest('#wordTip'))$('#wordTip').classList.add('hidden')});
function exerciseHeader(text){return `<div class="questionMascot"><img src="assets/lumi.png" alt="Lumi"><div class="bubble">${text}</div></div>`}
function renderExercise(){document.querySelector('.feedback')?.remove();if(run.i>=run.items.length||run.hearts<=0)return finishLesson();const e=run.items[run.i],w=e.w,p=Math.round(run.i/run.items.length*100);$('#lessonProgress').style.width=p+'%';$('#hearts').textContent='❤ '+run.hearts;run.answered=false;let h=`<div class="question">${exerciseHeader(promptFor(e.type))}`;
if(e.type==='choice'){const opts=shuffle([w.de,...distract(w,'de')]);h+=`<h1>Was bedeutet das Wort?</h1><div class="romanianPrompt">${clickableRomanian(w.ro,w.de)} <button class="miniAudio" id="play">🔊</button></div><p class="hint">Tippe das rumänische Wort an, um nur seine deutsche Bedeutung zu sehen.</p><div class="answers">${opts.map(o=>`<button class="answer" data-value="${esc(o)}">${esc(o)}</button>`).join('')}</div>`}
if(e.type==='sentenceChoice'){const opts=shuffle([w.deEx,...distract(w,'deEx')]);h+=`<h1>Was bedeutet der ganze Satz?</h1><div class="romanianPrompt">${clickableRomanian(w.roEx,w.deEx)} <button class="miniAudio" id="play">🔊</button></div><div class="answers">${opts.map(o=>`<button class="answer" data-value="${esc(o)}">${esc(o)}</button>`).join('')}</div>`}
if(e.type==='listenSentence'||e.type==='dictation'){h+=`<h1>${e.type==='listenSentence'?'Welchen Satz hörst du?':'Schreibe den gehörten Satz'}</h1><div class="audioPanel"><button class="audioBtn" id="play">🔊</button><button class="secondary" id="playSlow">🐢 Langsam</button></div>${e.type==='listenSentence'?`<div class="answers">${shuffle([w.deEx,...distract(w,'deEx')]).map(o=>`<button class="answer" data-value="${esc(o)}">${esc(o)}</button>`).join('')}</div>`:`<input class="typed" id="typed" autocomplete="off" placeholder="Rumänischen Satz schreiben …"><button class="primary wide" id="check">Prüfen</button>`}`}
if(e.type==='type'){h+=`<h1>Übersetze das Wort ins Rumänische</h1>${germanHintPrompt(w.de,w.ro)}<input class="typed" id="typed" autocomplete="off" placeholder="Auf Rumänisch schreiben …"><button class="primary wide" id="check">Prüfen</button>`}
if(e.type==='arrange'){const target=w.roEx.replace(/[.!?]/g,'');const pieces=shuffle(target.split(' '));h+=`<h1>Bilde den rumänischen Satz</h1><div class="germanPrompt">${esc(w.deEx)}</div><div class="arrangeTarget" id="target"></div><div class="chips">${pieces.map((x,i)=>`<button class="wordChip" data-word="${esc(x)}" data-n="${i}">${esc(x)}</button>`).join('')}</div><button class="primary wide" id="checkArrange">Prüfen</button>`}
if(e.type==='speak'||e.type==='freeSpeak'){h+=`<h1>${e.type==='speak'?'Sprich den Satz nach':'Sprich frei auf Rumänisch'}</h1><div class="romanianPrompt">${clickableRomanian(w.roEx,w.deEx)}</div><div class="translationLine"><b>Deutsch:</b> ${esc(w.deEx)}</div><div class="speakControls"><button class="secondary" id="modelAudio">🔊 Vorhören</button><button class="micBtn" id="mic">🎙️ Sprechen</button></div><div id="speechResult" class="speechResult">Tippe auf „Sprechen“ und sage den vollständigen Satz.</div><button class="primary wide hidden" id="acceptSpeech">Weiter</button>`}
if(e.type==='translateSentence'){h+=`<h1>Übersetze den ganzen Satz</h1>${germanHintPrompt(w.deEx,w.roEx.replace(/[.!?]/g,''))}<textarea class="typed area" id="typed" placeholder="Rumänischer Satz …"></textarea><button class="primary wide" id="check">Prüfen</button>`}
if(e.type==='story'){const st=e.story;h+=`<h1>Mini-Text: ${esc(D.categories.find(c=>c.id===run.lesson.section)?.title||'Alltag')}</h1><div class="storyCard"><div class="romanianPrompt">${clickableRomanian(st.ro,st.de)} <button class="miniAudio" id="play">🔊</button></div><details><summary>Deutsche Übersetzung anzeigen</summary><p>${esc(st.de)}</p></details></div><h2>${esc(st.q)}</h2><div class="answers">${st.answers.map((o,i)=>`<button class="answer" data-value="${i}">${esc(o)}</button>`).join('')}</div>`}
h+='</div>';$('#exercise').innerHTML=h;bindWordTips();bindGermanHints();
const audioText=e.type==='choice'||e.type==='type'?w.ro:e.type==='story'?e.story.ro:w.roEx;
if($('#play')){$('#play').onclick=()=>speak(audioText);setTimeout(()=>speak(audioText),250)}if($('#playSlow'))$('#playSlow').onclick=()=>speak(audioText,true);if($('#modelAudio'))$('#modelAudio').onclick=()=>speak(w.roEx);
$$('.answer').forEach(b=>b.onclick=()=>{let correct,sol;if(e.type==='story'){correct=String(e.story.correct);sol={ro:e.story.answers[e.story.correct],de:e.story.q}}else if(e.type==='choice'){correct=w.de;sol={ro:w.ro,de:w.de}}else if(e.type==='sentenceChoice'||e.type==='listenSentence'){correct=w.deEx;sol={ro:w.roEx,de:w.deEx}}else{correct=w.ro;sol=exerciseSolution(e,w)}checkAnswer(b,b.dataset.value,correct,w,1,sol)});
if($('#check')){$('#check').onclick=()=>{const sol=exerciseSolution(e,w);checkAnswer($('#typed'),$('#typed').value,sol.ro,w,1,sol)};$('#typed').onkeydown=x=>{if(x.key==='Enter'&&!x.shiftKey){x.preventDefault();$('#check').click()}}}
$$('.wordChip').forEach(b=>b.onclick=()=>{if(b.classList.contains('used'))return;b.classList.add('used');const c=document.createElement('button');c.className='wordChip';c.textContent=b.dataset.word;c.onclick=()=>{b.classList.remove('used');c.remove()};$('#target').append(c)});if($('#checkArrange'))$('#checkArrange').onclick=()=>{const sol=exerciseSolution(e,w);checkAnswer($('#target'),[...$('#target').children].map(x=>x.textContent).join(' '),sol.ro,w,1,sol)};if($('#mic'))$('#mic').onclick=()=>startRecognition(w);}
function promptFor(t){return {choice:'Bedeutung erkennen',listen:'Hör genau hin',type:'Schreibe auf Rumänisch',arrange:'Baue den Satz',speak:'Sprich Lumi nach',translateSentence:'Übersetze den Satz',dictation:'Hördiktat',freeSpeak:'Flüssigkeitstraining',sentenceChoice:'Satz verstehen',listenSentence:'Hörverständnis',story:'Lesen & verstehen'}[t]}
let mediaRecorder=null, recordedChunks=[], lastRecordingUrl='';
async function recordOwnVoice(){
  const btn=$('#recordOwn'), audio=$('#ownPlayback');
  if(!navigator.mediaDevices?.getUserMedia){toast('Tonaufnahme wird von diesem Browser nicht unterstützt.');return}
  if(mediaRecorder?.state==='recording'){mediaRecorder.stop();btn.textContent='🎙️ Eigene Stimme aufnehmen';return}
  try{
    const stream=await navigator.mediaDevices.getUserMedia({audio:true});
    recordedChunks=[]; mediaRecorder=new MediaRecorder(stream);
    mediaRecorder.ondataavailable=e=>{if(e.data.size)recordedChunks.push(e.data)};
    mediaRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());if(lastRecordingUrl)URL.revokeObjectURL(lastRecordingUrl);lastRecordingUrl=URL.createObjectURL(new Blob(recordedChunks,{type:mediaRecorder.mimeType||'audio/webm'}));audio.src=lastRecordingUrl;audio.classList.remove('hidden');audio.play().catch(()=>{});};
    mediaRecorder.start();btn.textContent='⏹ Aufnahme beenden';
  }catch(e){toast('Mikrofonzugriff wurde nicht erlaubt.')}
}
function startRecognition(w){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#speechResult').innerHTML='<b>Mikrofonerkennung nicht verfügbar.</b><span>Nutze Chrome/Edge oder eine aktuelle Browser-Version. Auf iPhone kann diese Funktion eingeschränkt sein.</span>';return}try{recognition?.abort()}catch{}recognition=new SR();recognition.lang='ro-RO';recognition.interimResults=false;recognition.maxAlternatives=3;const mic=$('#mic');mic.classList.add('recording');mic.textContent='● Höre zu …';$('#speechResult').textContent='Sprich jetzt den vollständigen Satz.';recognition.onresult=ev=>{const alternatives=[...ev.results[0]].map(x=>({text:x.transcript,confidence:x.confidence||0}));const best=alternatives.sort((a,b)=>similarity(b.text,w.roEx)-similarity(a.text,w.roEx))[0];const sim=similarity(best.text,w.roEx);const ok=sim>=.72;$('#speechResult').innerHTML=`<b>${ok?'Gut erkannt!':'Noch einmal üben'}</b><span>Erkannt: „${esc(best.text)}“</span><span>Zielsatz: ${clickableRomanian(w.roEx,w.deEx)}</span><span>Deutsch: ${esc(w.deEx)}</span><span>Übereinstimmung: ${Math.round(sim*100)} %</span>`;bindWordTips();mic.classList.remove('recording');mic.textContent='🎙️ Noch einmal';const next=$('#acceptSpeech');next.classList.remove('hidden');next.textContent=ok?'Als richtig werten':'Weiter mit Fehler';next.onclick=()=>checkAnswer(next,best.text,w.roEx,w,.72,{ro:w.roEx,de:w.deEx})};recognition.onerror=ev=>{mic.classList.remove('recording');mic.textContent='🎙️ Noch einmal';$('#speechResult').innerHTML=`<b>Spracherkennung fehlgeschlagen.</b><span>${esc(ev.error==='not-allowed'?'Mikrofonzugriff wurde nicht erlaubt. Bitte in den Browser-Einstellungen freigeben.':ev.error)}</span>`};recognition.onend=()=>{mic.classList.remove('recording');if(mic.textContent.includes('Höre'))mic.textContent='🎙️ Noch einmal'};recognition.start()}
function checkAnswer(el,given,correct,w,threshold=1,solution=null){if(run.answered)return;run.answered=true;const score=similarity(given,correct),ok=score>=threshold;const sol=solution||{ro:correct,de:w.de};S.answers++;if(ok){S.correct++;S.xp+=10;run.score++;S.wordStats[w.id]=(S.wordStats[w.id]||0)+1}else{run.hearts--;S.wordStats[w.id]=Math.max(0,(S.wordStats[w.id]||0)-1)}save();if(el.classList)el.classList.add(ok?'correct':'wrong');const box=document.createElement('div');box.className='feedback '+(ok?'':'wrong');box.innerHTML=`<div class="feedbackRow"><div><b>${ok?'Richtig! Foarte bine!':'Noch nicht ganz richtig.'}</b><small><strong>Rumänisch:</strong> ${clickableRomanian(sol.ro,sol.de)}</small><small><strong>Deutsch:</strong> ${esc(sol.de)}</small>${!ok?`<small><strong>Deine Antwort:</strong> ${esc(given||'–')}</small>`:''}<button class="feedbackAudio" id="feedbackAudio">🔊 Lösung anhören</button></div><button class="primary" id="next">Weiter</button></div>`;document.body.append(box);bindWordTips();$('#feedbackAudio').onclick=()=>speak(sol.ro);$('#next').onclick=()=>{box.remove();run.i++;renderExercise()}}
function continueCourse(){const next=LESSONS.find(l=>!S.completed[l.id])||LESSONS.at(-1);startLesson(next)}
function exportProgress(){const blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='lumi-fortschritt.json';a.click();URL.revokeObjectURL(a.href)}
$('#continueCourse').onclick=continueCourse;if($('#dialoguesNav'))$('#dialoguesNav').onclick=showDialogues;$('#dialoguesBtn').onclick=showDialogues;$('#storiesBtn').onclick=showStories;$('#grammarBtn').onclick=showGrammar;$('#reviewBtn').onclick=()=>$('#practiceBtn').click();


function runSelfTest(){
  const results=[];const check=(name,ok)=>results.push({name,ok:!!ok});
  try{check('Daten geladen',D.words.length>=240);check('Lernpfad erzeugt',LESSONS.length===180);check('Grammatik vorhanden',X.grammar.length>=10);check('Dialoge vorhanden',X.dialogues.length>=10);check('Geschichten vorhanden',X.stories.length>=5);check('Glossar geladen',G.length>=5000);check('Erste Lektion frei',lessonUnlocked(0));startLesson(LESSONS[0]);check('Übung startet',!!run&&run.items.length>=8);show('#screenPath');renderCourse();check('Lernpunkte gerendert',$$('.node').length===180)}catch(e){results.push({name:'Laufzeit',ok:false,error:String(e)})}
  const box=document.createElement('pre');box.id='selftest';box.textContent=JSON.stringify(results);document.body.append(box);
}

renderStats();renderCourse();show('#screenPath');if('speechSynthesis'in window){loadVoices();speechSynthesis.onvoiceschanged=loadVoices}if(new URLSearchParams(location.search).has('selftest'))setTimeout(runSelfTest,150);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js?v=7').catch(()=>{});
