
(()=>{
const cats=[
['basics','Grundlagen'],['questions','Fragen'],['numbers','Zahlen & Zeit'],['family','Familie'],['home','Zuhause'],['food','Essen'],['shopping','Einkaufen'],['city','Öffentliches Leben'],['transport','Verkehr'],['travel','Reisen'],['health','Gesundheit'],['work','Arbeit'],['school','Lernen'],['leisure','Freizeit'],['nature','Natur'],['feelings','Gefühle'],['media','Technik'],['society','Gesellschaft'],['culture','Kultur'],['communication','Diskussion'],['science','Wissenschaft'],['business','Wirtschaft'],['advanced','Fortgeschritten'],['idioms','Alltagssprache']];
const scenarios={
basics:['Begrüßung','Vorstellen','Höflich nachfragen','Verabschiedung','Small Talk'],questions:['Nach Namen fragen','Nach dem Weg fragen','Nach Uhrzeit fragen','Etwas klären'],numbers:['Termin vereinbaren','Preis nennen','Geburtstag','Uhrzeit'],family:['Familie vorstellen','Besuch planen','Über Geschwister sprechen','Familienfest'],home:['Wohnung beschreiben','Haushalt teilen','Problem in der Wohnung'],food:['Im Restaurant','Im Café','Einkaufen im Supermarkt','Rezept besprechen'],shopping:['Preis erfragen','Umtausch','An der Kasse','Kleidung kaufen'],city:['Bei der Bank','Auf dem Amt','In der Post','Nach einer Adresse fragen'],transport:['Am Bahnhof','Im Bus','Taxi bestellen','Autopanne'],travel:['Im Hotel','Am Flughafen','Ausflug planen','Reservierung'],health:['Beim Arzt','In der Apotheke','Beschwerden erklären','Notfall'],work:['Im Büro','Telefonat mit Kollegen','Besprechung','Bewerbung'],school:['Im Unterricht','Hausaufgaben','Prüfung','Sprachkurs'],leisure:['Fußball','Kino','Wochenende','Training'],nature:['Wetter','Wandern','Tiere','Umwelt'],feelings:['Über Gefühle sprechen','Streit klären','Dating','Entschuldigung'],media:['Handyproblem','Online-Termin','Nachrichten','Soziale Medien'],society:['Behörde','Regeln','Wahlen','Nachbarschaft'],culture:['Museum','Traditionen','Geschichte','Konzert'],communication:['Meinung begründen','Widersprechen','Kompromiss','Präsentation'],science:['Forschung erklären','Klima','Gesundheitstechnologie'],business:['Vertrag','Preisverhandlung','Finanzen','Projekt'],advanced:['Abstrakte Diskussion','Analyse','Formeller Brief'],idioms:['Umgangssprache','Redewendungen','Humor','Spontanes Gespräch']};
const lines=[
['Bună ziua! Cu ce vă pot ajuta?','Guten Tag! Wie kann ich Ihnen helfen?'],['Aș dori mai multe informații.','Ich hätte gern mehr Informationen.'],['Puteți repeta, vă rog?','Können Sie das bitte wiederholen?'],['Desigur. Vă explic imediat.','Natürlich. Ich erkläre es Ihnen sofort.'],['Mulțumesc pentru ajutor.','Danke für die Hilfe.'],['Cu plăcere.','Gern geschehen.'],['La ce oră începe?','Um wie viel Uhr beginnt es?'],['Unde trebuie să merg?','Wohin muss ich gehen?'],['Cât costă?','Wie viel kostet es?'],['Am înțeles.','Ich habe verstanden.']];
let dialogues=[];let id=1;
for(const [cat,title] of cats){const ss=scenarios[cat]||[title];for(let r=0;r<42;r++){const s=ss[r%ss.length];const level=r<10?'A1':r<20?'A2':r<30?'B1':r<38?'B2':'C1';const off=(r*3+cat.length)%lines.length;const turns=[];for(let i=0;i<6;i++){const x=lines[(off+i)%lines.length];turns.push([i%2?'B':'A',x[0],x[1]])}dialogues.push({id:id++,cat,level,title:s+' '+(r+1),scene:`Situation: ${s}. Antworte höflich und natürlich.`,turns});}}
dialogues=dialogues.slice(0,1000);
const storySeeds={basics:['Ana begrüßt eine neue Nachbarin.','Mihai stellt sich im Sprachkurs vor.'],family:['Eine Familie plant den Sonntag.','Ein Besuch bei den Großeltern.'],food:['Ein Abend im Restaurant.','Einkauf für ein gemeinsames Essen.'],transport:['Eine verspätete Zugfahrt.','Die Suche nach der richtigen Bushaltestelle.'],travel:['Ankunft im Hotel.','Ein Tag am Meer.'],health:['Ein Termin beim Arzt.','Ein Besuch in der Apotheke.'],work:['Ein neuer Arbeitstag.','Eine wichtige Besprechung.'],feelings:['Ein Missverständnis wird geklärt.','Zwei Freunde sprechen offen miteinander.']};
let stories=[];id=1;
for(const [cat,title] of cats){for(let n=0;n<13;n++){const level=n<3?'A1':n<6?'A2':n<9?'B1':n<11?'B2':'C1';const seed=(storySeeds[cat]||[`Eine Alltagssituation zum Thema ${title}.`])[n%2];const ro=level==='A1'?`Ana este în oraș. Ea vorbește cu o persoană și pune o întrebare simplă. Persoana răspunde încet. Ana înțelege și spune mulțumesc.`:level==='A2'?`Ana are o situație legată de ${title.toLowerCase()}. Mai întâi caută informații, apoi discută cu o persoană. După câteva întrebări găsește o soluție potrivită.`:level==='B1'?`Într-o zi aglomerată, Ana trebuie să rezolve o problemă legată de ${title.toLowerCase()}. Ea compară mai multe posibilități, cere explicații și decide ce variantă este mai practică.`:level==='B2'?`Situația devine mai complexă, deoarece fiecare soluție are avantaje și dezavantaje. Ana își explică opinia, ascultă argumentele celorlalți și încearcă să ajungă la un compromis realist.`:`Pentru a lua o decizie responsabilă, Ana analizează contextul, consecințele pe termen lung și perspectivele diferite. Ea formulează o concluzie nuanțată și își justifică alegerea.`;
const de=level==='A1'?`Ana ist in der Stadt. Sie spricht mit einer Person und stellt eine einfache Frage. Die Person antwortet langsam. Ana versteht und bedankt sich.`:level==='A2'?`Ana erlebt eine Situation zum Thema ${title}. Zuerst sucht sie Informationen, dann spricht sie mit einer Person. Nach einigen Fragen findet sie eine passende Lösung.`:level==='B1'?`An einem vollen Tag muss Ana ein Problem zum Thema ${title} lösen. Sie vergleicht mehrere Möglichkeiten, bittet um Erklärungen und entscheidet, welche Variante praktischer ist.`:level==='B2'?`Die Situation wird komplexer, weil jede Lösung Vor- und Nachteile hat. Ana erklärt ihre Meinung, hört die Argumente der anderen und versucht, einen realistischen Kompromiss zu finden.`:`Um verantwortungsvoll zu entscheiden, analysiert Ana den Kontext, langfristige Folgen und unterschiedliche Perspektiven. Sie formuliert ein differenziertes Fazit und begründet ihre Wahl.`;
stories.push({id:id++,cat,level,title:`${title}: Geschichte ${n+1}`,seed,ro,de,question:'Was macht Ana in dieser Geschichte?',answers:['Sie sucht eine passende Lösung.','Sie ignoriert die Situation.','Sie verlässt sofort den Ort.'],correct:0});}}
stories=stories.slice(0,300);
window.LUMI_MEGA={dialogues,stories,cats};
})();
